server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/geosus_paciente
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jackson:
    serialization:
      INDENT_OUTPUT: true

# (opcional) para permitir testes locais com CORS
# cors:
#   allowed-origins: "*"
