server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-paciente:5432/geosus_paciente
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

    springdoc:
      swagger-ui:
        path: /swagger-ui.html
      api-docs:
        path: /v3/api-docs


  jackson:
    serialization:
      INDENT_OUTPUT: true
